### ISSUE TITLE
Not compatible with the version of your running IDE (Gateway 2024.2.3, PyCharm 2024.3 EAP)

### ISSUE THREAD

**Issue by mrba59** [adrianboguszewski/debug-image-viewer#5]
It seems that the plugin can't be found when we connect to a remote server, is it possible to add this option ? When i try to install it from disk i get this error message :

Plugin 'Debug Image Viewer (former OpenCV Image Viewer)' (version '4.1.0') is not compatible with the current version of the IDE, because it requires build 242.* or older but the current build is PY-243.18137.1

**Comment by adrianboguszewski** [comment]
Hey @mrba59, PyCharm 2024.3 is still EAP, so the support in 4.1.0 is unavailable. However, I'll release the new version of the plugin before the release of 2024.3. For now, I recommend using 2024.2 or 2024.1.

**Comment by adrianboguszewski** [comment]
@mrba59 the new version of the plugin (which supports 2024.3) has been released! Feel free to update it :)

**Comment by ivan-stp** [comment]
Can you please update it so it works in Rider? Latest supported Rider version is 2024.3.8

**Comment by adrianboguszewski** [comment]
Hi @ivan-stp. Debug Image Viewer has been acquired by JetBrains, so I cannot change anything in the product anymore. Please talk to them directly.

**Comment by ivan-stp** [comment]
Got it, thanks
